# Generated by Django 5.1.1 on 2024-11-10 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='per',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perid', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('dob', models.CharField(max_length=100)),
                ('sx', models.CharField(max_length=100)),
                ('ambition', models.CharField(max_length=100)),
                ('lan', models.CharField(max_length=100)),
                ('add', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='cc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cer', models.CharField(max_length=300)),
                ('person1id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume11.per')),
            ],
        ),
        migrations.CreateModel(
            name='aca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cs', models.CharField(max_length=100)),
                ('sch_clg', models.CharField(max_length=500)),
                ('uni', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('per', models.CharField(max_length=100)),
                ('personid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume11.per')),
            ],
        ),
    ]
