# Generated by Django 5.1.1 on 2024-11-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume11', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='per',
            name='perid',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
