# Generated by Django 5.1.1 on 2024-11-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume11', '0002_alter_per_perid'),
    ]

    operations = [
        migrations.AddField(
            model_name='per',
            name='ph_no',
            field=models.IntegerField(default=3, max_length=100),
            preserve_default=False,
        ),
    ]
