# Generated by Django 5.1.1 on 2024-11-12 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume11', '0003_per_ph_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='per',
            name='gmail',
            field=models.CharField(default=4, max_length=100),
            preserve_default=False,
        ),
    ]
