# Generated by Django 5.1.1 on 2024-11-12 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume11', '0004_per_gmail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='per',
            old_name='gmail',
            new_name='mail',
        ),
    ]
