# Generated by Django 5.1.1 on 2024-11-12 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume11', '0005_rename_gmail_per_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='per',
            name='ph_no',
            field=models.IntegerField(max_length=10),
        ),
    ]
